### ISSUE TITLE
Buidling automation for stress test & monitoring

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2082] opened 2021-03-01 11:26 UTC
Building the stress test in an automated way in order to test on a regular basis > Weekly

<p></p>

Items to be performed with Jina's official terraform module:
- [x] Enable [jinad-aws](https://registry.terraform.io/modules/jina-ai/jinad-aws/jina/latest) to create multiple JinaD instances (pods) in one vpc
- [x] Enable installation of pip packages (and other commands execution) on different instances before starting JinaD.

Stress-tests:
- [x] Use `jinad-aws` to start multiple remote Pods. Create one more instance (client) & run [stress-tests.](https://github.com/jina-ai/cloud-ops/tree/master/stress-example).
- [x] Once the tests run for few hours, destroy all resources (this is tricky). 
- [x] Send performance stats to a slack channel.
- [x] Enable github actions to schedule the automated run. 
- [x] Use Wiki dataset for the stress test

**Comment by lusloher** [comment] 2021-03-01 11:26
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/7141006

**Comment by FionnD** [comment] 2021-05-17 07:26
Hi @deepankarm 

Is this issue done?

**Comment by jacobowitz** [comment] 2021-05-19 17:35
This issue is implemented now, lets keep the issue open until we discussed it and close it beginning of next week?

**Comment by jacobowitz** [comment] 2021-05-28 09:00
I removed the G2G timing now as it is broken.
There is still a problem that the processing time of one executor can be pontially totally off, this is due to this bug:
https://github.com/jina-ai/jina/issues/2500

Unfortunately, there is nothing to be done about this from a stress test perspective.

**Comment by deepankarm** [comment] 2021-05-28 11:03
@jacobowitz We should close this ticket now, as the issue is tracked separately.

**Comment by deepankarm** [comment] 2021-05-28 11:57
@FionnD, I won't call it blocked. I would say, because of stress-tests, we used `routes` & found a bug there :D. Having G2G timing is not absolutely mandatory, let's close this ticket.

**Comment by FionnD** [comment] 2021-05-28 12:07
Ok, closed

**Closed** 2021-05-28 12:07 UTC
Labels: area/housekeeping, epic/Benchmarking, priority/important-soon, type/feature-request
