### ISSUE TITLE
[client] [Errno 2] No such file or directory:  '($PWD)/uvloop/loop.pyx'

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/jina#4813] opened 2022-05-20 15:26 UTC
**Describe the bug**
After roughly 5 minutes and 20 seconds my indexing Flow stops and this error comes up (as long as I'm indexing enough Documents to take over 5 minutes and 20 seconds - 10k, 45k, it always happens. But with 1 or 10 it exits normally).

I'm using latest version of Jina, but it's happened with other versions too. Things still seem to get indexed, though how it's difficult to say.

I'll put my indexing code in a comment for reference

```
╭─────────────────────── Traceback (most recent call last) ────────────────────────╮
│ /mnt/data/work/repos/personal/fashion_search/backend/app.py:68 in <module>       │
│                                                                                  │
│   65                                                                             │
│   66                                                                             │
│   67 if __name__ == "__main__":                                                  │
│ ❱ 68 │   main()                                                                  │
│   69                                                                             │
│                                                                                  │
│ /mnt/data/work/repos/personal/fashion_search/env/lib/python3.9/site-packages/cli │
│ ck/core.py:1128 in __call__                                                      │
│                                                                                  │
│   1125 │                                                                         │
│   1126 │   def __call__(self, *args: t.Any, **kwargs: t.Any) -> t.Any:           │
│   1127 │   │   """Alias for :meth:`main`."""                                     │
│ ❱ 1128 │   │   return self.main(*args, **kwargs)                                 │
│   1129                                                                           │
│   1130                                                                           │
│   1131 class Command(BaseCommand):                                               │
│                                                                                  │
│ /mnt/data/work/repos/personal/fashion_search/env/lib/python3.9/site-packages/cli │
│ ck/core.py:1053 in main                                                          │
│                                                                                  │
│   1050 │   │   try:                                                              │
│   1051 │   │   │   try:                                                          │
│   1052 │   │   │   │   with self.make_context(prog_name, args, **extra) as ctx:  │
│ ❱ 1053 │   │   │   │   │   rv = self.invoke(ctx)                                 │
│   1054 │   │   │   │   │   if not standalone_mode:                               │
│   1055 │   │   │   │   │   │   return rv                                         │
│   1056 │   │   │   │   │   # it's not safe to `ctx.exit(rv)` here!               │
│                                                                                  │
│ /mnt/data/work/repos/personal/fashion_search/env/lib/python3.9/site-packages/cli │
│ ck/core.py:1395 in invoke                                                        │
│                                                                                  │
│   1392 │   │   │   echo(style(message, fg="red"), err=True)                      │
│   1393 │   │                                                                     │
│   1394 │   │   if self.callback is not None:                                     │
│ ❱ 1395 │   │   │   return ctx.invoke(self.callback, **ctx.params)                │
│   1396 │                                                                         │
│   1397 │   def shell_complete(self, ctx: Context, incomplete: str) -> t.List["Co │
│   1398 │   │   """Return a list of completions for the incomplete value. Looks   │
│                                                                                  │
│ /mnt/data/work/repos/personal/fashion_search/env/lib/python3.9/site-packages/cli │
│ ck/core.py:754 in invoke                                                         │
│                                                                                  │
│    751 │   │                                                                     │
│    752 │   │   with augment_usage_errors(__self):                                │
│    753 │   │   │   with ctx:                                                     │
│ ❱  754 │   │   │   │   return __callback(*args, **kwargs)                        │
│    755 │                                                                         │
│    756 │   def forward(                                                          │
│    757 │   │   __self, __cmd: "Command", *args: t.Any, **kwargs: t.Any  # noqa:  │
│                                                                                  │
│ /mnt/data/work/repos/personal/fashion_search/backend/app.py:58 in main           │
│                                                                                  │
│   55 │   if task == "index":                                                     │
│   56 │   │   index(CSV_FILE, num_docs=num_docs)                                  │
│   57 │   elif task == "cloud_index":                                             │
│ ❱ 58 │   │   cloud_index(host=CLOUD_HOST, csv_file=CSV_FILE, num_docs=num_docs)  │
│   59 │   elif task == "cloud_search":                                            │
│   60 │   │   cloud_search(host=CLOUD_HOST)                                       │
│   61 │   elif task == "serve":                                                   │
│                                                                                  │
│ /mnt/data/work/repos/personal/fashion_search/backend/app.py:24 in cloud_index    │
│                                                                                  │
│   21 │   client = Client(host=host)                                              │
│   22 │   docs = DocumentArray.from_csv(csv_file, size=num_docs)                  │
│   23 │   process_docs(docs)                                                      │
│ ❱ 24 │   client.post("/update", docs, show_progress=True)                        │
│   25                                                                             │
│   26                                                                             │
│   27 def cloud_search(host):                                                     │
│                                                                                  │
│ /mnt/data/work/repos/personal/fashion_search/env/lib/python3.9/site-packages/jin │
│ a/clients/mixin.py:161 in post                                                   │
│                                                                                  │
│   158 │   │   │   if return_results:                                             │
│   159 │   │   │   │   return result                                              │
│   160 │   │                                                                      │
│ ❱ 161 │   │   return run_async(                                                  │
│   162 │   │   │   _get_results,                                                  │
│   163 │   │   │   inputs=inputs,                                                 │
│   164 │   │   │   on_done=on_done,                                               │
│                                                                                  │
│ /mnt/data/work/repos/personal/fashion_search/env/lib/python3.9/site-packages/jin │
│ a/helper.py:1343 in run_async                                                    │
│                                                                                  │
│   1340 │   │   │   │   'please report this issue here: https://github.com/jina-a │
│   1341 │   │   │   )                                                             │
│   1342 │   else:                                                                 │
│ ❱ 1343 │   │   return get_or_reuse_loop().run_until_complete(func(*args, **kwarg │
│   1344                                                                           │
│   1345                                                                           │
│   1346 def slugify(value):                                                       │
│                                                                                  │
│ /mnt/data/work/repos/personal/fashion_search/backend/uvloop/loop.pyx:1501 in     │
│ uvloop.loop.Loop.run_until_complete                                              │
│                                                                                  │
│ [Errno 2] No such file or directory:                                             │
│ '/mnt/data/work/repos/personal/fashion_search/backend/uvloop/loop.pyx'           │
│                                                                                  │
│ /mnt/data/work/repos/personal/fashion_search/env/lib/python3.9/site-packages/jin │
│ a/clients/mixin.py:152 in _get_results                                           │
│                                                                                  │
│   149 │   │                                                                      │
│   150 │   │   async def _get_results(*args, **kwargs):                           │
│   151 │   │   │   result = [] if return_responses else DocumentArray()           │
│ ❱ 152 │   │   │   async for resp in c._get_results(*args, **kwargs):             │
│   153 │   │   │   │   if return_results:                                         │
│   154 │   │   │   │   │   if return_responses:                                   │
│   155 │   │   │   │   │   │   result.append(resp)                                │
│                                                                                  │
│ /mnt/data/work/repos/personal/fashion_search/env/lib/python3.9/site-packages/jin │
│ a/clients/base/http.py:76 in _get_results                                        │
│                                                                                  │
│    73 │   │   │   │   │   request_handler=_request_handler,                      │
│    74 │   │   │   │   │   result_handler=_result_handler,                        │
│    75 │   │   │   │   )                                                          │
│ ❱  76 │   │   │   │   async for response in streamer.stream(request_iterator):   │
│    77 │   │   │   │   │   r_status = response.status                             │
│    78 │   │   │   │   │                                                          │
│    79 │   │   │   │   │   r_str = await response.json()                          │
│                                                                                  │
│ /mnt/data/work/repos/personal/fashion_search/env/lib/python3.9/site-packages/jin │
│ a/serve/stream/__init__.py:78 in stream                                          │
│                                                                                  │
│    75 │   │   │   else self._stream_requests(request_iterator)                   │
│    76 │   │   )                                                                  │
│    77 │   │   try:                                                               │
│ ❱  78 │   │   │   async for response in async_iter:                              │
│    79 │   │   │   │   yield response                                             │
│    80 │   │   except InternalNetworkError as err:                                │
│    81 │   │   │   if (                                                           │
│                                                                                  │
│ /mnt/data/work/repos/personal/fashion_search/env/lib/python3.9/site-packages/jin │
│ a/serve/stream/__init__.py:154 in _stream_requests                               │
│                                                                                  │
│   151 │   │   while not all_requests_handled.is_set():                           │
│   152 │   │   │   future = await result_queue.get()                              │
│   153 │   │   │   try:                                                           │
│ ❱ 154 │   │   │   │   response = self._result_handler(future.result())           │
│   155 │   │   │   │   yield response                                             │
│   156 │   │   │   │   requests_to_handle.count -= 1                              │
│   157 │   │   │   │   update_all_handled()                                       │
│                                                                                  │
│ /mnt/data/work/repos/personal/fashion_search/env/lib/python3.9/site-packages/jin │
│ a/clients/base/helper.py:84 in send_message                                      │
│                                                                                  │
│    81 │   │   req_dict['exec_endpoint'] = req_dict['header']['exec_endpoint']    │
│    82 │   │   if 'target_executor' in req_dict['header']:                        │
│    83 │   │   │   req_dict['target_executor'] = req_dict['header']['target_execu │
│ ❱  84 │   │   return await self.session.post(url=self.url, json=req_dict).__aent │
│    85 │                                                                          │
│    86 │   async def recv_message(self):                                          │
│    87 │   │   """Receive message for HTTP (sleep)                                │
│                                                                                  │
│ /mnt/data/work/repos/personal/fashion_search/env/lib/python3.9/site-packages/aio │
│ http/client.py:1138 in __aenter__                                                │
│                                                                                  │
│   1135 │   │   return self.__await__()                                           │
│   1136 │                                                                         │
│   1137 │   async def __aenter__(self) -> _RetType:                               │
│ ❱ 1138 │   │   self._resp = await self._coro                                     │
│   1139 │   │   return self._resp                                                 │
│   1140                                                                           │
│   1141                                                                           │
│                                                                                  │
│ /mnt/data/work/repos/personal/fashion_search/env/lib/python3.9/site-packages/aio │
│ http/client.py:559 in _request                                                   │
│                                                                                  │
│    556 │   │   │   │   │   │   try:                                              │
│    557 │   │   │   │   │   │   │   resp = await req.send(conn)                   │
│    558 │   │   │   │   │   │   │   try:                                          │
│ ❱  559 │   │   │   │   │   │   │   │   await resp.start(conn)                    │
│    560 │   │   │   │   │   │   │   except BaseException:                         │
│    561 │   │   │   │   │   │   │   │   resp.close()                              │
│    562 │   │   │   │   │   │   │   │   raise                                     │
│                                                                                  │
│ /mnt/data/work/repos/personal/fashion_search/env/lib/python3.9/site-packages/aio │
│ http/client_reqrep.py:913 in start                                               │
│                                                                                  │
│    910 │   │   │   │                                                             │
│    911 │   │   │   │   if self._continue is not None:                            │
│    912 │   │   │   │   │   set_result(self._continue, True)                      │
│ ❱  913 │   │   │   │   │   self._continue = None                                 │
│    914 │   │                                                                     │
│    915 │   │   # payload eof handler                                             │
│    916 │   │   payload.on_eof(self._response_eof)                                │
│                                                                                  │
│ /mnt/data/work/repos/personal/fashion_search/env/lib/python3.9/site-packages/aio │
│ http/helpers.py:721 in __exit__                                                  │
│                                                                                  │
│   718 │   │   │   self._tasks.pop()                                              │
│   719 │   │                                                                      │
│   720 │   │   if exc_type is asyncio.CancelledError and self._cancelled:         │
│ ❱ 721 │   │   │   raise asyncio.TimeoutError from None                           │
│   722 │   │   return None                                                        │
│   723 │                                                                          │
│   724 │   def timeout(self) -> None:                                             │
╰──────────────────────────────────────────────────────────────────────────────────╯
TimeoutError
```

**Describe how you solve it**
No idea

---

**Environment**
```
- jina 3.4.4
- docarray 0.13.5
- jina-proto 0.1.10
- jina-vcs-tag (unset)
- protobuf 3.20.1
- proto-backend cpp
- grpcio 1.46.0
- pyyaml 6.0
- python 3.9.9
- platform Linux
- platform-release 5.10.114-1-MANJARO
- platform-version #1 SMP PREEMPT Mon May 9 07:52:55 UTC 2022
- architecture x86_64
- processor
- uid 242011234364068
- session-id 33e25c34-d851-11ec-99dc-dc1ba1a7eaa4
- uptime 2022-05-20T17:26:21.424270
- ci-vendor (unset)
* JINA_AUTH_TOKEN (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DEFAULT_WORKSPACE_BASE /home/alexcg/.jina/executor-workspace
* JINA_DEPLOYMENT_NAME (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_GRPC_RECV_BYTES (unset)
* JINA_GRPC_SEND_BYTES (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_NO_IMAGE_REBUILD (unset)
* JINA_HUB_ROOT (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_MP_START_METHOD (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)
* JINA_CHECK_VERSION True
```

**Screenshots**

**Comment by alexcg1** [comment] 2022-05-20 15:26
UVLoop is clearly installed, since it'll happily index a few hundred without throwing errors

**Comment by alexcg1** [comment] 2022-05-20 15:29
Code:

```python
server = "https://0df596d980.wolf.jina.ai"
client = Client(host=server)
client.post("/update", docs, show_progress=True)
```

It's connecting to [this Flow](https://github.com/jina-ai/example-multimodal-fashion-search/blob/main/backend/jcloud/flow.yml) in JCloud

That said, I've seen same bug outside of using it with JCloud

**Comment by JoanFM** [comment] 2022-05-20 16:04
It seems that uvloop is not installed

**Comment by alexcg1** [comment] 2022-05-21 13:00
It's installed. I checked. And it's not even looking for it in my venv, but rather in the dir where I run my app. And it actually does run fine, for 5 minutes and ~20 seconds. Then it spits out that error.

I did a check for uvloop install via `pip list | grep uvloop`:

```
uvloop                    0.16.0
```

**Comment by alexcg1** [comment] 2022-05-21 13:01
Any time I index just a few Documents that don't even take 5 minutes 20 seconds, it does its thing properly and ends perfectly normally

**Comment by alexcg1** [comment] 2022-05-23 13:26
Doing some additional debugging on this. Since Flow is behind JCloud there's not a lot I can do on that end, but:

- It takes a while for me to connect to JCloud after the indexing crashes - maybe the Flow has totally choked on something and needs to clear its throat (so to speak) (tho it registers as `ALIVE` still via `jc list`)

## Replicate the problem

- Run `python app.py -t cloud_index -n 50000` to index 50k documents (this runs an `/update` operation, so assume skips all content that's already-indexed)
- It works for ~5 minutes (this time it's 5:05, not 5:20) then times out
- Query `/status` endpoint to get index size
- Rinse and repeat

After running it several times I get different `total_docs` in index:

- 1600
- 2000
- 2000 (still)
- 2000 (still)

I queried using my [JFC](https://github.com/alexcg1/jfc) tool, which calls `status` endpoint and prints result

![image](https://user-images.githubusercontent.com/4182659/169827129-f6a25e41-7db7-49e4-a684-430e3addbe81.png)

## Thoughts

- It always takes about 5 minutes to time out (sometimes a bit more, up to 5:30 in my exp so far)
- It times out after processing 2000 Documents, or after the index fills with 2000 Documents. I'm not sure which.
- Since It's using PQLiteIndexer it requires unique Document IDs, so I assume every Document in index is unique

## Ideas to fix

- I'll try upgrading to ANNIndexer
- I'll try upping the memory for the indexer

This will mean re-deploying the Flow on JCloud so I'll be starting with a fresh one.

I don't think this will make a difference, but I'll give it a shot

**Comment by JoanFM** [comment] 2022-05-23 13:36
@deepankarm this 5 minutes reminds me of some default timeout. I think this may have to do with prefetching or with having `Flow` exposed via `http` and the need to serialize `tensors`? 

Are you trying to return `tensors` in the resulting `DocumentArrays` via `http` @alexcg1 ?

**Comment by alexcg1** [comment] 2022-05-23 13:43
Nope. In the indexing Flow I have an Executor that specifically deletes tensors. It only stores embeddings + metadata (which includes URL to actual image). So I don't need tensors at all.

I mean, tensors go in (cuz we need them for encoding), but they don't come out.

My Flow:
```yaml
jtype: Flow
with:
  protocol: http
  cors: true
executors:
  - name: encoder
    uses: jinahub+docker://CLIPEncoder/v0.3.0
    resources:
      memory: 8G
  - name: tensor_deleter
    uses: jinahub+docker://TensorDeleter
  - name: indexer
    uses: jinahub+docker://AnnLiteIndexer/0.3.0
    resources:
      memory: 1G
    uses_with:
      dim: 512
      metric: cosine
      include_metadata: true
      columns:
        - ['year', 'int']
        - ['productDisplayName', 'str']
        - ['usage', 'str']
        - ['subCategory', 'str']
        - ['masterCategory', 'str']
        - ['articleType', 'str']
        - ['season', 'str']
        - ['baseColour', 'str']
        - ['gender', 'str']
        - ['price', 'int']
        - ['rating', 'int']
    uses_metas:
      workspace: workspace
```

Note: I just tried deploying this with 1G of memory on new JCloud instance and got same problem. This happened after indexing 700 Documents this time, It's always a round number so maybe this isn't just a timeout?

**Comment by alexcg1** [comment] 2022-05-23 13:44
For reference, here's code for TensorDeleter:

```python
from jina import Executor, DocumentArray, requests, Document


def process_doc(doc: Document):
    if hasattr(doc, "tensor"):
        doc.tensor = None

    return doc


class TensorDeleter(Executor):
    @requests
    def remove_tensor(self, docs: DocumentArray, **kwargs):
        docs.apply(process_doc)
```

I last changed it pre-DocArray, hence the old imports

**Comment by JoanFM** [comment] 2022-05-23 13:46
hey @alexcg1, may u also try to remove the embedding and make sure that at the end both `tensors` and `embeddings` are gone?

**Comment by JoanFM** [comment] 2022-05-24 13:43
I am quite convinced it is an issue with converting tensors into `json`

**Comment by alexcg1** [comment] 2022-05-24 13:43
Even with empty Flow running on http, it times out after 5 minutes 23 seconds. Just tried now

**Comment by alexcg1** [comment] 2022-05-24 13:44
It's definitely an http thing

**Comment by JoanFM** [comment] 2022-05-24 14:31
If you want to use `http` protocol, u want to make 100% sure that `Documents` do not have `tensors` when returning and also when sending potentially. So yes, u can set `blob` or `uri`.

**Comment by JoanFM** [comment] 2022-05-25 07:33
Closing as root cause seems clear! Ticket is open for clarifying in documentation #4825

**Closed by JoanFM** 2022-05-25 07:33 UTC

**Comment by alexcg1** [comment] 2022-05-25 10:36
Hmmm....this really overcomplicates building RESTful search engines, which is a pretty common use case. Most of the Hub Executors take tensors as input, so having to add an extra Executor in the middle just to turn blobs back into tensors feels inelegant and kludgy.

**Comment by JoanFM** [comment] 2022-05-25 11:39
this problem is a docarray issue, and is a well known issue with no solution, you can also fork the Executor to drop it. Or you can use `GraphQL` endpoint to remove `tensors` from the `response`
