### ISSUE TITLE
check tests/integration/instrumentation flakyness

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#5545] opened 2022-12-21 09:54 UTC
**Describe the bug**
This test  tests/integration/instrumentation looks very flaky and do not let us work with 3.8

**Comment by girishc13** [comment] 2023-01-17 15:45
The root cause is due to improper shutdown of the opentelmetry grpc client. Each test is creating all docker dependencies and then destroying at the end of the test. Since the client running in a different thread doesn't shutdown properly and leads to a segmentation fault. The gprc client has a very large back off 64s which is long compared to the length of the test execution.

**Comment by girishc13** [comment] 2023-01-17 15:51
Ref: 
- https://github.com/open-telemetry/opentelemetry-python/issues/1791
- https://github.com/open-telemetry/opentelemetry-python/blob/edf4d6cd07b5ea922180b52c9e737b7be0d59f9f/exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/exporter.py#L263

**Comment by girishc13** [comment] 2023-01-19 16:43
Additional errors from the slack thread.
```
status {
  code: ERROR
  description: "InterfaceError(\'Error binding parameter 1 - probably unsupported type.\')"
  exception {
    name: "InterfaceError"
    args: "Error binding parameter 1 - probably unsupported type."
    stacks: "Traceback (most recent call last):\n"
    stacks: "  File \"/home/matt/anaconda2/envs/jina/lib/python3.8/site-packages/jina/serve/runtimes/worker/__init__.py\", line 264, in process_data\n    result = await self._request_handler.handle(\n"
    stacks: "  File \"/home/matt/anaconda2/envs/jina/lib/python3.8/site-packages/jina/serve/runtimes/worker/request_handling.py\", line 425, in handle\n    return_data = await self._executor.__acall__(\n"
    stacks: "  File \"/home/matt/anaconda2/envs/jina/lib/python3.8/site-packages/jina/serve/executors/__init__.py\", line 366, in __acall__\n    return await self.__acall_endpoint__(req_endpoint, **kwargs)\n"
    stacks: "  File \"/home/matt/anaconda2/envs/jina/lib/python3.8/site-packages/jina/serve/executors/__init__.py\", line 425, in __acall_endpoint__\n    return await exec_func(\n"
    stacks: "  File \"/home/matt/anaconda2/envs/jina/lib/python3.8/site-packages/jina/serve/executors/__init__.py\", line 383, in exec_func\n    return await get_or_reuse_loop().run_in_executor(\n"
    stacks: "  File \"/home/matt/anaconda2/envs/jina/lib/python3.8/concurrent/futures/thread.py\", line 57, in run\n    result = self.fn(*self.args, **self.kwargs)\n"
    stacks: "  File \"/home/matt/anaconda2/envs/jina/lib/python3.8/site-packages/jina/serve/executors/decorators.py\", line 187, in arg_wrapper\n    return fn(executor_instance, *args, **kwargs)\n"
    stacks: "  File \"/home/matt/.cache/jina/hub-package/zb38xlt4/executor.py\", line 66, in index\n    self._index.extend(docs)\n"
    stacks: "  File \"/home/matt/anaconda2/envs/jina/lib/python3.8/site-packages/docarray/array/storage/base/seqlike.py\", line 81, in extend\n    self._extend(values, **kwargs)\n"
    stacks: "  File \"/home/matt/anaconda2/envs/jina/lib/python3.8/site-packages/docarray/array/storage/sqlite/seqlike.py\", line 77, in _extend\n    self._append(doc, commit=False)\n"
    stacks: "  File \"/home/matt/anaconda2/envs/jina/lib/python3.8/site-packages/docarray/array/storage/sqlite/seqlike.py\", line 43, in _append\n    self._sql(\n"
    stacks: "  File \"/home/matt/anaconda2/envs/jina/lib/python3.8/site-packages/docarray/array/storage/sqlite/backend.py\", line 41, in _sql\n    return self._cursor.execute(*args, **kwargs)\n"
    stacks: "sqlite3.InterfaceError: Error binding parameter 1 - probably unsupported type.\n"
    executor: "SimpleIndexer"
  }
}
```

**Comment by girishc13** [comment] 2023-01-23 16:02
Waiting for review of https://github.com/open-telemetry/opentelemetry-python/pull/3138.

**Comment by girishc13** [comment] 2023-01-23 16:07
The instrumentation worker runs in a daemon thread/s in:
- https://github.com/open-telemetry/opentelemetry-python/blob/fa19e1f3753d622697bb4d69d394409c6127158e/opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/export/__init__.py#L469
- https://github.com/open-telemetry/opentelemetry-python/blob/fa19e1f3753d622697bb4d69d394409c6127158e/opentelemetry-sdk/src/opentelemetry/sdk/trace/export/__init__.py#L195. 
 
Is there a way to make sure that this thread terminates before closing the Flow context manager. The logs clearly show that the exporter is still working in the background due to the max 64s exponential back off retry logic.

**Comment by JoanFM** [comment] 2023-01-23 16:19
Every Runtime is ensured to call the `cancel` and so on, we may be able to close it there

**Comment by JoanFM** [comment] 2023-01-23 16:21
Ww should be able to call this `shutdown` https://github.com/open-telemetry/opentelemetry-python/blob/fa19e1f3753d622697bb4d69d394409c6127158e/opentelemetry-sdk/src/opentelemetry/sdk/trace/export/__init__.py#L412 somewhere?

**Comment by JoanFM** [comment] 2023-01-23 16:21
And this one:

https://github.com/open-telemetry/opentelemetry-python/blob/fa19e1f3753d622697bb4d69d394409c6127158e/opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/export/__init__.py#L510

**Comment by girishc13** [comment] 2023-01-23 16:24
The runtime already does call the [shutdown](https://github.com/jina-ai/jina/blob/master/jina/serve/runtimes/asyncio.py#L93-L106) but the code doesn't break the exponential back off and retry loop. I have asked a question in my pr regarding the cancellation of the retry after shutdown is set.

**Comment by JoanFM** [comment] 2023-01-24 17:51
Seems related to https://bugs.python.org/issue39853 and the same problem as https://github.com/astropy/astropy/issues/10008

**Closed** 2023-01-25 10:42 UTC
Labels: epic/gRPCTransport
