### ISSUE TITLE
Flask is mentioned as an extra dependency when it should be fastapi

### ISSUE THREAD

**Issue by samjoy** [jina-ai/jina#1931] opened 2021-02-11 16:51 UTC
In https://docs.jina.ai/chapters/install/os/via-pip.html, under the Extra Dependencies Explained section, you mention using flask as one of your extra dependencies. Didn't you make a shift from flask to fastapi as mentioned here jina-ai/jina#1348.

**Comment by FionnD** [comment] 2021-02-12 14:58
Hey @samjoy 

Thanks for highlighting! 

@deepankarm should this be changed in our docs?

**Comment by nan-wang** [comment] 2021-02-15 03:51
hi, @samjoy Many thanks for pointing out the issue. The problem is the whole section on [extra dependency](https://docs.jina.ai/chapters/install/os/via-pip.html#extra-dependencies-explained) is not up-to-date.

**Comment by FionnD** [comment] 2021-02-15 07:50
Hi @nan-wang 

I wonder is there a way we could automatically pull the [extra-requirements.txt](https://github.com/jina-ai/jina/blob/master/extra-requirements.txt) into the docs repo and phrase it as .rst? This would save future updates 🤔 .

**Comment by LukeekuL** [comment] 2021-02-21 14:24
Hi, 

I have updated the extra dependencies section according to extra-requierements.txt. Regarding automation, I think the problem is also the additional columns "Description" and "Compatibility" which are not present in the extra-requierements.txt file. Dropping them would simplify the update process and automation.

**Comment by FionnD** [comment] 2021-02-21 17:36
Hi @LukeekuL , 

Thanks for fixing it! 

Good point about the automation, I suspect it would be possible to some regex, but maybe not worth the effort. 

I will be closing this issue now 👍

**Closed by FionnD** 2021-02-21 17:36 UTC
Labels: documentation, good first issue, priority/P2
