### ISSUE TITLE
Flow is hanging when using multi-threading

### ISSUE THREAD

**Issue by Yongxuanzhang** [jina-ai/jina#2527] opened 2021-06-01 01:04 UTC
**Describe the bug**

Flow is hanging when adding RuntimeBackendType.THREAD into one executor in the flow.
![image](https://user-images.githubusercontent.com/44033547/120252881-d1a11100-c253-11eb-8e42-bfa002044b9a.png)

**To reproduce it:**

```
from jina import Flow
from jina.enums import RuntimeBackendType

f = Flow().add(name='p1').add(name='p2').add(name='p3',needs='p2').add(name='p4', runtime_backend=RuntimeBackendType.THREAD).add(name='p5').add(name='p6',needs='p2').add(name='p7',needs=['p6','p5'])
f.plot()
with f:
    pass
```
---

**Environment**

jina==2.0.0rc2.dev57

**Screenshots**

**Comment by Yongxuanzhang** [comment] 2021-06-01 01:18
To address this, use it at Flow level instead:

```
from jina import Flow
from jina.enums import RuntimeBackendType

f = Flow(runtime_backend=RuntimeBackendType.THREAD).add(name='p1').add(name='p2').add(name='p3',needs='p2').add(name='p4').add(name='p5').add(name='p6',needs='p2').add(name='p7',needs=['p6','p5'])
f.plot()
with f:
    pass
```

**Comment by JoanFM** [comment] 2021-06-01 13:56
It is curious, if u remove the `last` pod it seems to work

**Comment by jacobowitz** [comment] 2021-06-02 10:42
Code to reproduce the issue without Jina:

```
import multiprocessing
import threading


def process_target():
    import slow_module
    print('process done')


def thread_target():
    import slow_module
    print(f'thread done')


p = multiprocessing.Process(target=process_target)
t = threading.Thread(target=thread_target)
t.start()
p.start()
t.join()
p.join()

print(f'done')
```

slow_module being something like this:
```
from time import sleep

sleep(1.0)
```

**Comment by FionnD** [comment] 2021-06-03 08:41
Closing this issue because it the feature will be added in #2527

**Closed by FionnD** 2021-06-03 08:41 UTC
Labels: area/core, type/bug
