### ISSUE TITLE
websocket: ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')

### ISSUE THREAD

**Issue by sbmaruf** [jina-ai/jina#2461] opened 2021-05-21 13:03 UTC
Hi! 

New Jina user. Not sure if this is a bug or not. But posting for attention.

I have successfully run Jina's example https://github.com/jina-ai/examples/tree/master/multires-lyrics-search

While I am trying to adapt this to my own dataset, I am getting following error,

```
encoder@14234[I]:recv IndexRequest  from gateway▸segmenter/ZEDRuntime▸encoder/ZEDRuntime▸⚐
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<WebSocketClientMixin._get_results.<locals>._send_requests() done, defined at /data/sbmaruf/anaconda3/envs/pt3.8-search/lib/python3.8/site-packages/jina/clients/websocket.py:66> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "/data/sbmaruf/anaconda3/envs/pt3.8-search/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 750, in transfer_data
    message = await self.read_message()
  File "/data/sbmaruf/anaconda3/envs/pt3.8-search/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 819, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/data/sbmaruf/anaconda3/envs/pt3.8-search/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 895, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/data/sbmaruf/anaconda3/envs/pt3.8-search/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 971, in read_frame
    frame = await Frame.read(
  File "/data/sbmaruf/anaconda3/envs/pt3.8-search/lib/python3.8/site-packages/websockets/legacy/framing.py", line 55, in read
    data = await reader(2)
  File "/data/sbmaruf/anaconda3/envs/pt3.8-search/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/data/sbmaruf/anaconda3/envs/pt3.8-search/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/sbmaruf/anaconda3/envs/pt3.8-search/lib/python3.8/site-packages/jina/clients/websocket.py", line 68, in _send_requests
    await websocket.send(next_request.SerializeToString())
  File "/data/sbmaruf/anaconda3/envs/pt3.8-search/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 471, in send
    await self.ensure_open()
  File "/data/sbmaruf/anaconda3/envs/pt3.8-search/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
index takes 1 minute and 55 seconds (115.11s)
        ✅ done in ⏱ 1 minute and 55 seconds 🐎 13.6/s
WebSocketClient@9896[E]:Got following error while streaming requests via websocket: ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')
```

What's more interesting is that, if I'm running it with GPU (since I'm using distill-BERT) it hangs, but if I'm running it on CPU it continues. 

Since exceptions are throwing in running code in CPU, I'm not sure how many documents have been indexed. Is there any way to verify how many documents have been successfully indexed? I cannot find any information in the log.

From the time elapsed and the size of the workspace, I could understand, though the indexing continues in CPU, it stops as soon as it found an exception.

**Comment by alexcg1** [comment] 2021-05-25 16:14
This looks a lot like [an error I had a while ago](https://github.com/jina-ai/examples/issues/474#issuecomment-825548014)

Can you run `jina -v` and post the output so we can know what version you're using. And this error is after running `python app.py -t index`, right?

**Comment by sbmaruf** [comment] 2021-05-26 02:47
1. Jina version is showing `1.2.0`.
2. Yes, I'm using `python app.py -t index`
3. Just to add an additional note (if it helps), I am trying to index documents. The documents are supposed to be long. May be [here](https://github.com/jina-ai/jina/blob/master/jina/clients/websocket.py#L56 ) the max_size needs to be updated. Note that the original example works fine.

**Comment by JoanFM** [comment] 2021-05-26 06:35
Hey @sbmaruf ,

Thanks for reporting, The `max_size` should not affect since the error code related to this is 1009 while here we are getting a 1006

**Comment by deepankarm** [comment] 2021-05-26 06:57
@sbmaruf We set `max_size` to None to[ disable the limit](https://github.com/aaugustin/websockets/blob/main/src/websockets/legacy/client.py#L94) of the maximum size of incoming messages. That shouldn't be causing the issue with large documents. Your issue seems to be related to a missing `PONG` from server for a `PING` from the client. Let me try to reproduce it at my end today.

**Comment by deepankarm** [comment] 2021-05-26 11:51
@sbmaruf While I try reproducing this at my end, can you change [restful: False](https://github.com/jina-ai/examples/blob/master/multires-lyrics-search/flows/index.yml#L4) in the flow yaml. This would use gRPC server + client for streaming documents into Jina instead of websockets.

**Comment by alexcg1** [comment] 2021-06-01 15:05
@sbmaruf any luck?

**Comment by sbmaruf** [comment] 2021-06-04 01:01
> @sbmaruf While I try reproducing this at my end, can you change [restful: False](https://github.com/jina-ai/examples/blob/master/multires-lyrics-search/flows/index.yml#L4) in the flow yaml. This would use gRPC server + client for streaming documents into Jina instead of websockets.

@alexcg1  @deepankarm 

Sorry for the late. Got patched into a conference deadline. `gRPC server + client` works. I wish I could share my data for plain re-producibility. But I don't have permission to share my data.

I found another hack. [Here](https://github.com/jina-ai/jina/blob/master/jina/clients/websocket.py#L56) I add one additional parameter, `ping_timeout=2000` and then it continues indexing. I think it is safe to add a longer timeout.

**Comment by cristianmtr** [comment] 2021-06-04 14:48
Hey @sbmaruf 

Thanks for providing more info on this. I think this PR https://github.com/jina-ai/jina/pull/2564 fixes this problem. 

Can you try to reproduce it now?

**Comment by sbmaruf** [comment] 2021-06-06 15:13
Yes, I can confirm. It's working. Theoretically, it should work ( :) ). Earlier I was trying with a number and you just make it infinite.

**Comment by alexcg1** [comment] 2021-06-07 10:02
@sbmaruf great to hear it's working now! If no objection I'll go ahead and close this issue

**Closed** 2021-06-07 13:03 UTC
Labels: type/bug
