### ISSUE TITLE
new endpoints for daemon

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#1704] opened 2021-01-15 20:14 UTC
**Describe the feature**

I often worry about the zombie pea/pod/flow in daemon. Think daemon as a "windows task manager", would be nice to have the following endpoints:

- GET `/alive` -> `/status`: show also the summary of the store
- GET `/pea`: get all running pea ids in the store, if it is in the store but not alive mark it as a zombie.
- GET `/pod`: same but on pod level
- GET `/flow`:  same but on flow level

**Your proposal**

---

**Environment**

**Screenshots**

**Comment by deepankarm** [comment] 2021-01-16 05:55
Possible duplicate of https://github.com/jina-ai/jina/issues/1688 ?

**Comment by deepankarm** [comment] 2021-01-16 09:51
https://github.com/dmontagu/fastapi-utils/blob/master/fastapi_utils/tasks.py
There's already an implementation of a decorator to run a job periodically, which can be done for the Zombie check (rather than integrating that with an API endpoint).

**Closed** 2021-01-19 22:45 UTC
Labels: area/daemon, kind/feature
