### ISSUE TITLE
GRPCClient not working

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#3250] opened 2021-08-23 15:22 UTC
Reproduce:

`flow.py`
```
from jina import Flow

with Flow(host='127.0.0.1', protocol='grpc', port_expose=8085) as f:
    f.block()
```

`client.py`
```
from jina.clients.grpc import GRPCClient

client = GRPCClient(host='127.0.0.1', port_expose=8085, protocol='grpc')
print(client.search(inputs=[{'text': 't1'}], return_results=True))
```

`exception`
```
Traceback (most recent call last):
  File "/Users/florianhonicke/jina/jina/bug.py", line 9, in <module>
    print(client.search(inputs=[{'text': 't1'}], return_results=True))
  File "/Users/florianhonicke/jina/jina/jina/clients/mixin.py", line 70, in post
    **kwargs,
  File "/Users/florianhonicke/jina/jina/jina/helper.py", line 1167, in run_async
    return asyncio.run(func(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/florianhonicke/jina/jina/jina/clients/mixin.py", line 53, in _get_results
    async for resp in c._get_results(*args, **kwargs):
  File "/Users/florianhonicke/jina/jina/jina/clients/base/grpc.py", line 92, in _get_results
    raise BadClient(msg) from rpc_ex
jina.excepts.BadClient: gRPC error: StatusCode.UNKNOWN Unexpected <class 'BrokenPipeError'>: [Errno 32] Broken pipe
```

**Comment by deepankarm** [comment] 2021-08-24 02:48
Changing `flow.py` to below should fix it.

```python
from jina import Flow

with Flow(protocol='grpc', port_expose=8085) as f:
    f.block()
```

The issue is because we don't support `host` arg with `Flow` yet.

**Comment by JoanFM** [comment] 2021-08-25 07:45
But @deepankarm @florian-hoenicke ,

Then the problem should be that '127.0.0.1' is not the right host for the client when running locally right? I understand that if u point the client to the proper address it should connect right?

Should we close this then?

**Comment by jacobowitz** [comment] 2021-08-30 08:58
It works with this flow

```
with Flow(host='0.0.0.0', protocol='grpc', port_expose=8085) as f:
    f.block()
```

I think its debatable if that is a bug or not. @florian-hoenicke What is the reasoning of trying to do this?

**Comment by JoanFM** [comment] 2021-09-26 17:04
Closing, if it is considered a bug can be opened again

**Closed by JoanFM** 2021-09-26 17:04 UTC
