### ISSUE TITLE
Enable systemd based daemon deployment to cloud.jina.ai with CD

### ISSUE THREAD

**Issue by deepankarm** [jina-ai/jina#1772] opened 2021-01-24 11:28 UTC
**Describe the feature**
Using AWS cfn/terraform templates to deploy latest daemon code can be deployed to cloud.jina.ai.

**Comment by FionnD** [comment] 2021-03-03 16:14
Duplicate of https://github.com/jina-ai/jina/issues/2068

**Closed** 2021-03-03 16:13 UTC
Labels: type/feature-request
