### ISSUE TITLE
varies errors in embeddings setter

### ISSUE THREAD

**Issue by bwanglzu** [jina-ai/jina#3546] opened 2021-10-01 08:10 UTC
note: this happens sometime, for the `embeddings` setter in `da` and `dam`:

context: worked with @tadejsv on refactoring executors, we set:

```python
batch_generator = docs.batch(...)
for batch in batch_generator:
    batch.embeddings = embeddings
```

(previously it was a for loop, set `embedding` one by one)
different errors pop-up, for example:
1. [TypeError('embedding is in unsupported type tensorflow.python.framework.ops.EagerTensor')](https://github.com/jina-ai/executors/runs/3753742753)
2. [TypeError: data type '' not understood](https://github.com/jina-ai/executors/runs/3753739451)
3. [raise TypeError("sparse matrix length is ambiguous; use getnnz()"](https://github.com/jina-ai/executors/runs/3753743096)

and maybe more. i tried the following scripts, it works fine in a normal case:

```python
import numpy as np
from jina import Document, DocumentArray

docs = DocumentArray([Document(text=str(i)) for i in range(100)])
batch_size = 10

document_batches_generator = docs.batch(
    traversal_paths=('r',),
    batch_size=batch_size,
    require_attr="text",
)


if __name__ == '__main__':
    for batch in document_batches_generator:
        batch.embeddings = np.random.rand(batch_size, 100)

    for doc in docs:
        assert doc.embedding.shape == (100, )

```

**Comment by JoanFM** [comment] 2021-10-01 09:53
Closing as the problem is the type of input

**Closed by JoanFM** 2021-10-01 09:53 UTC
Labels: focus/ease-of-use
