### ISSUE TITLE
Cannot use JinaHub, network error

### ISSUE THREAD

**Issue by luisArandas** [jina-ai/jina#4596] opened 2022-04-11 13:58 UTC
Hello all.

I'm currently getting a bug every time I try to get something from the hub. The first bug is: 
```
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate 
(_ssl.c:1129)

During handling of the above exception, another exception occurred:

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate 
(_ssl.c:1129)>
```

I didn't solve it, trying in a few hours if this persists. Does this have to do with the servers of the company being down? Or is it an installation error on my side? I'm running Jina on my `Macbook Pro (Retina, 15-inch, Mid 2015) macOS Monterey v12.2`.

- jina 3.2.10
- docarray 0.12.1
- jina-proto 0.1.8
- jina-vcs-tag (unset)
- protobuf 3.20.0
- proto-backend cpp
- grpcio 1.44.0
- pyyaml 6.0
- python 3.9.5
- platform Darwin
- platform-release 21.3.0
- platform-version Darwin Kernel Version 21.3.0: Wed Jan 5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
- architecture x86_64
- processor i386
- uid 119394988065483
- session-id 6b8269fc-b99f-11ec-8cf2-6c96cfda02cb
- uptime 2022-04-11T14:58:09.365613
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_DEPLOYMENT_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)

Thanks!

**Comment by luisArandas** [comment] 2022-04-11 14:11
Hello @JoanFM. Yes absolutely, so that bug on the previous comment is for the common `jina hello multimodal`, it starts when I start downloading. And I seem to have the same bug when adding hub models such as with the import `.add(uses="jinahub://SpacyTextEncoder", name="encoder", install_requirements=True)` for example. 

`⠋ Fetching SpacyTextEncoder from Jina Hub ...           JINA@3380[C]:Can not fetch the Url of Hubble from api.jina.ai
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate 
`

**Comment by cristianmtr** [comment] 2022-04-11 14:38
I couldn't reproduce this issue @luisArandas . Might be some issue with your local certificate storage. Are you on Mac? There is a solution [here](https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate) it seems

**Comment by cristianmtr** [comment] 2022-04-11 15:01
Awesome @luisArandas . I'll close this issue now. Let us know if you get into other issues

**Closed by cristianmtr** 2022-04-11 15:01 UTC
