### ISSUE TITLE
Chaining Multiple flows

### ISSUE THREAD

**Issue by mirfan899** [jina-ai/jina#3879] opened 2021-11-07 04:56 UTC
**Describe your proposal/problem**
I'm looking for chaining the flows with different ports. For example, I'm trying to run multilingual model with different flows.

For now, I have to create flows for each language i.e. English, Spanish, Chinese etc for exposing the ports and sending post to these flows. Here is English flow on port 12345

```python
flow = Flow(port_expose=12345, protocol='http', cors=True).add(name="encoder", uses='jinahub://TransformerTorchEncoder',
        uses_with={'pretrained_model_name_or_path': '/semantic-search/distiluse-base-multilingual-cased-v1'}).add(
        uses="jinahub://SimpleIndexer", name="indexer", install_requirements=True,
        uses_metas={"workspace": "workspace/en"}
```

Spanish Flow.
```python
flow = Flow(port_expose=12346, protocol='http', cors=True).add(name="encoder", uses='jinahub://TransformerTorchEncoder',
        uses_with={'pretrained_model_name_or_path': '/semantic-search/distiluse-base-multilingual-cased-v1'}).add(
        uses="jinahub://SimpleIndexer", name="indexer", install_requirements=True,
        uses_metas={"workspace": "workspace/es"})
```

For now I have to run different flow to work with. I'm using different workspace for searching. Is there any other way to do it?

**Comment by mirfan899** [comment] 2021-11-09 15:19
any update?

**Comment by JoanFM** [comment] 2021-11-09 15:36
Hello @mirfan899, sorry for the late reply.

It would be good to know what is your intention, Do u want to have 2 different applications where the client knows where to send the request (is it spanish or not), or u want to chain 2 Flows one after the other?.

What you can do is to use shared executors between different Flows as described here: 
https://docs.jina.ai/fundamentals/flow/add-exec-to-flow/?highlight=spawned#add-remote-executor

It would be cool to know the intended usecase so that we can recommend the best approach

**Comment by mirfan899** [comment] 2021-11-09 15:56
Thanks for reply. I am looking to have at least two flows for English and Spanish, where I can send request by specifying the language. Because when I used the single flow for different languages, results are being mixed i.e. English query showing both English and Spanish search results. 

I tried to use parallel processing to spawn the different flows for each language, but no flow was being generated in multiprocessing approach. 

```python
import multiprocessing as mp
from jina import Flow


def run(job):
    en = Flow(port_expose=12346, protocol='http', cors=True).add(name="encoder",
                    uses='jinahub://TransformerTorchEncoder',
                    uses_with={'pretrained_model_name_or_path': 'semantic-search/distiluse-base-multilingual-cased-v1'}).add(
                    uses="jinahub://SimpleIndexer", name="indexer", install_requirements=True,
                    uses_metas={"workspace": "workspace/{}".format(job)})
    with en:
        en.block()


def main():
    jobs = ["en", "es"]
    pool = mp.Pool(len(jobs))
    print("Total Parallel Jobs Starting *********************** {}".format(jobs))
    for index, job in enumerate(jobs):
        pool.apply_async(run, args=(index, job, ))
    # wait for the n_jobs to complete
    pool.close()
    pool.join()
    print("Zipping files to output.zip +++++++++++++++++++++++++++")


if __name__ == "__main__":
    main()
```

I was hoping to generate flow for each language on different ports so that I can index and search for each language.

**Comment by JoanFM** [comment] 2021-11-09 16:07
Hey @mirfan899 ,

what is the error u receive? I think this would fail because `run` receives a single argument but u are passing 2.

However, a proper way could be this.

```python
import multiprocessing as mp
from jina import Flow


def run(job):
    en = Flow(port_expose=12346, protocol='http', cors=True).add(name="encoder",
                    uses='jinahub://TransformerTorchEncoder',
                    uses_with={'pretrained_model_name_or_path': 'semantic-search/distiluse-base-multilingual-cased-v1'}).add(
                    uses="jinahub://SimpleIndexer", name="indexer", install_requirements=True,
                    uses_metas={"workspace": "workspace/{}".format(job)})
    with en:
        en.block()


def main():
    jobs = ["en", "es"]
    pool =[]
    print("Total Parallel Jobs Starting *********************** {}".format(jobs))
    for index, job in enumerate(jobs):
        p = multiprocessing.Process(target=run, kwargs={'job': job})
        p.start()
    # wait for the n_jobs to complete
    for p in pool:
        p.join()
   


if __name__ == "__main__":
    main()



```

**Comment by mirfan899** [comment] 2021-11-09 16:34
Thanks, It seems working now.

**Comment by CatStark** [comment] 2021-11-10 13:25
Hi @mirfan899 good to hear the problem is solved. I will close the issue then, please open a new ticket if you have another problem.

**Closed by CatStark** 2021-11-10 13:25 UTC

**Comment by mirfan899** [comment] 2021-11-12 10:20
Hi, after looking working with parallel code, I have found a problem with it. 

Here is what `jina` does when you try to use two different flows. I use English data to index it on English port. Data is indexed using client from `jina`. It index the data for English and Spanish data as well which is very strange because both flows are running on two different ports and both are using two different workspace.

When I run the English and Spanish flow independently it works fine.

Here is how I'm running the parallel flow and testing it with script.


```python
import multiprocessing

from jina import Flow

PORTS = {"en": 11111,
         "es": 22222,
         }

def run(job):
    flow = Flow(port_expose=PORTS[job], protocol="http", cors=True).add(name="encoder",
                uses="jinahub://TransformerTorchEncoder",
                uses_with={"device": "cuda", "pretrained_model_name_or_path": "./semantic-search/distiluse-base-multilingual-cased-v1"}).add(
        uses="jinahub://SimpleIndexer", name="indexer", install_requirements=True,
        uses_metas={"workspace": "workspace/{}".format(job)})
    with flow:
        flow.block()


def main():
    # jobs = ["en", "es", "zh", "ar"]
    jobs = ["en", "es"]
    pool = []

    print("Total Parallel Jobs Starting *********************** {}".format(jobs))
    for index, job in enumerate(jobs):
        p = multiprocessing.Process(target=run, kwargs={'job': job})
        p.start()
        pool.append(p)
    # wait for the n_jobs to complete
    for p in pool:
        p.join()


if __name__ == "__main__":
    main()
```

Here is the client code to test it to reproduce the issue.

```python
import os
from jina import Client, Document
from jina.types.request import Response
import click

from helpers import PORTS


def input_generator(file_path: str):
    with open(file_path) as file:
        lines = file.readlines()

    name = os.path.basename(file_path)
    for i in lines:
        yield Document(text=i, uri=name)


@click.command()
@click.option("--file", "-f", type=str)
@click.option("--language", "-l", type=click.Choice(["en", "ar"]), default="en")
def main(file, language):
    print(language)

    if language == "en":
        c = Client(protocol="http", port=PORTS[language])  # connect to arabic
        c.post('/index', inputs=input_generator(file), show_progress=True)
    elif language == "ar":
        c = Client(protocol="http", port=PORTS[language])  # connect to english
        c.post('/index', inputs=input_generator(file), show_progress=True)


if __name__ == "__main__":
    main()
```

Here is quick look into how to run the index script
```shell
python index.py  -f ./data/en/toy.txt -l en
```
Jina creates two indexes instead of one.
![jina_indexer](https://user-images.githubusercontent.com/3822565/141451186-439215bf-617e-4296-8361-e2465ce49f9a.png)

**Comment by JoanFM** [comment] 2021-11-12 11:29
Hey @mirfan899 ,

I do not see exactly the problem? You are saying that the `english` data is found under `es` index? The fact that files are created does not imply that data is there. Have u checked how much documents are in each of these indexes?

To try this a workaround u can do is:

```python
from jina import DocumentArrayMemmap

dam_es = DocumentArrayMemmap('es/SimpleIndexer/0')
dam_en =  DocumentArrayMemmap('en/SimpleIndexer/0')

print(f' Documents in Spanish index {len(dam_es)}')
print(f' Documents in English index {len(dam_en)}')
```

**Comment by mirfan899** [comment] 2021-11-12 14:49
Here is the output. English index throws error but spanish index does not.
```python
from jina import DocumentArrayMemmap
dam_en = DocumentArrayMemmap('workspace/en/SimpleIndexer/0')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/irfan/.pyenv/versions/Jina/lib/python3.7/site-packages/jina/types/arrays/memmap.py", line 98, in __init__
    self._load_header_body()
  File "/home/irfan/.pyenv/versions/Jina/lib/python3.7/site-packages/jina/types/arrays/memmap.py", line 131, in _load_header_body
    ('', np.int64),  # 8 bytes
ValueError: buffer size must be a multiple of element size
```
