### ISSUE TITLE
Make sure hubio disk_cache_offline work on mac

### ISSUE THREAD

**Issue by Yongxuanzhang** [jina-ai/jina#3234] opened 2021-08-20 15:42 UTC
**Describe the bug**

have docker installed
```
docker run --add-host host.docker.internal:host-gateway \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v /tmp/jinad:/tmp/jinad \
           -p 8000:8000 \
           --name jinad \
           -d jinaai/jina:master-daemon
from jina import Flow, Document

f = Flow().add(uses='jinahub://SimpleRanker', host='localhost:8000')

with f:
    f.post(on="/index",inputs=Document())
 File "/usr/local/lib/python3.7/site-packages/daemon/api/endpoints/partial/pea.py", line 39, in _create
    return store.add(args)

  File "/usr/local/lib/python3.7/site-packages/daemon/stores/partial.py", line 65, in add
    self.object: Union['Pea', 'Pod'] = self.peapod_cls(args).__enter__()

  File "/usr/local/lib/python3.7/site-packages/jina/peapods/peas/__init__.py", line 127, in __init__
    self.runtime_cls = self._get_runtime_cls()

  File "/usr/local/lib/python3.7/site-packages/jina/peapods/peas/__init__.py", line 382, in _get_runtime_cls
    set_hub_pull_parser().parse_args([self.args.uses, '--no-usage'])

  File "/usr/local/lib/python3.7/site-packages/jina/hubble/hubio.py", line 696, in pull
    raise e

  File "/usr/local/lib/python3.7/site-packages/jina/hubble/hubio.py", line 630, in pull
    executor = HubIO._fetch_meta(name, tag=tag, secret=secret)

  File "/usr/local/lib/python3.7/site-packages/jina/hubble/helper.py", line 279, in wrapper
    with shelve.open(cache_file) as cache_db:

  File "/usr/local/lib/python3.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)

  File "/usr/local/lib/python3.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)

  File "/usr/local/lib/python3.7/dbm/__init__.py", line 94, in open
    return mod.open(file, flag, mode)

_gdbm.error: [Errno 2] No such file or directory
```
**Describe how you solve it**

Environment

```
Mac OS Catalina Version 10.15.5
jina 2.0.19

jina-proto 0.0.85
jina-vcs-tag (unset)
libzmq 4.3.3
pyzmq 1.19.5
protobuf 3.14.0
proto-backend cpp
grpcio 1.34.1
pyyaml 5.3.1
python 3.7.9
platform Darwin
platform-release 19.5.0
platform-version Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020;
root:xnu-6153.121.2~2/RELEASE_X86_64
architecture x86_64
processor i386
```
Describe how you solve it

Environment

Screenshots

**Comment by deepankarm** [comment] 2021-08-21 07:03
This is partially solved in https://github.com/jina-ai/jina/pull/3236, since jinad is where we see this issue. 

It was because `with shelve.open(cache_file) as cache_db:` couldn't open the file `/root/.jina/disk_cache.db` file in a non-existing `/root/.jina` directory. This would be a common issue in all places `Path.home()` is used. This can be fixed by setting `$HOME` to `/workspace` for all containers created by JinaD.  

Another issue is, we shouldn't fail in `disk_cache_offline` decorator if `shelve` cannot open this file, as it only does performance optimization.

**Comment by mapleeit** [comment] 2021-11-26 09:38
Confirmed no error occurs now. Closing

**Closed by mapleeit** 2021-11-26 09:38 UTC
Labels: type/bug
