### ISSUE TITLE
CI pipeline timeouts randomly

### ISSUE THREAD

**Issue by fhaase2** [jina-ai/jina#607] opened 2020-07-01 19:21 UTC
**Describe your problem**

CI pipeline takes 19 minutes and times out randomly (without error on PR). This is not critical, but might get worse if we add more test cases.

Issue is already known. Might be due to resources (such as sockets, processes and threads) are not released properly during the individual tests.

One solution could be to run tests in individual processes (see e.g here: https://pypi.org/project/pytest-xdist/ or https://pypi.org/project/pytest-forked/ or some other solution such as https://pypi.org/project/nose/ which also supports that AFAIK).

**What is your guess?**

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment] 2020-07-01 20:58
Let me add the comments from our chat.

> CI timeouts randomly and it's not due to some time-consuming tests, but because Python/unittest module fail to release resources, e.g. socket, process and thread. Sometime it means we open too many sockets and randomly hit a socket that we didn't release.
> 
> - Empirically, a 19m-failed-CI always means a false-positive. In other word, you just got unlucky. Click into details and hit rerun the test you probably get through.
> - A true-positive test fails early. If you see a failed test in < 10min, then it must be the problem of PR.
> - Successful test takes ~11m on py3.7 and ~8m on py 3.8, not because the latter is faster, but because more test cases are enabled in 3.7.
> - It is possible that you run tests two times, one with 3.7 pass 3.8 fails one with the other way around. In this case, you can conclude it is false-positive and you just get unlucky.

**Comment by hanxiao** [comment] 2020-07-05 12:28
Related issue: https://github.com/pytest-dev/pytest/issues/3310

**Comment by hanxiao** [comment] 2020-07-09 15:21
we really need to solve this problem asap. this seriously slows down the merging process @nan-wang

**Comment by JoanFM** [comment] 2020-07-09 15:58
I have not investigated much, but it really is a problem and can potentially slow down the process. Could it be caused by having the PY37 and PY38 tests run in parallel?

**Comment by fhaase2** [comment] 2020-07-09 16:08
@hanxiao would `pytest-forked` be an acceptable solution for you? Cause it does not seem to be really maintained.

**Comment by hanxiao** [comment] 2020-07-09 17:54
we can try pytest-forked. i’m listing the potential troublemakers that may break pytest-forked:
- asyncio and ioloop
- multiprocessing and multithread
- calling Docker container
- frequent socket opening and closing

**Comment by hanxiao** [comment] 2020-07-12 07:59
@nan-wang can you push forward and set up due on this? This issue is really blocking everything.

**Comment by hanxiao** [comment] 2020-07-12 08:15
> I have not investigated much, but it really is a problem and can potentially slow down the process. Could it be caused by having the PY37 and PY38 tests run in parallel?

Py37 and py38 are running in parallel but in different instances. This should not be a problem.

**Comment by nan-wang** [comment] 2020-07-12 10:18
> @nan-wang can you push forward and set up due on this? This issue is really blocking everything.

I'm on it.

**Comment by nan-wang** [comment] 2020-07-13 03:03
There are several issues behind our current ci failures:

1. first of all, the port conflicts during testing. This is not fully solved with `pytest-xdist`. I've set it to use single thread, but we still need some luck to get the tests passed. I guess we still need some `sleep()` for recycling the ports. [partly fixed]
2. The usage of `extract_chunks` in the `Drivers` is broken. **[fixed]** It is a dirty fix, but this part will be refactored anyway in [https://github.com/jina-ai/jina/pull/647](https://github.com/jina-ai/jina/pull/647)
3. The side-effects of switching unittests to `discovery` mode has not fully solved. Some relative path is still broken. **[fixed]**
4. The unittests on customtorch and customkeras import the libraries. **[fixed]**
5. `test_gateway.py` brokes the CI. **[skipped]** Need some time to dig into it.
6. `test_quant.py` brokes the CI. **[skipped]** Need some time to dig into it.

**Comment by nan-wang** [comment] 2020-07-13 03:31
The remaining issue of port conflicts,

```bash
2020-07-13T03:23:08.7767065Z ERROR:root:Exception iterating responses: Address already in use
2020-07-13T03:23:08.7767307Z Traceback (most recent call last):
2020-07-13T03:23:08.7768524Z   File "/home/runner/work/jina/jina/jina/peapods/grpc_asyncio.py", line 90, in _take_response_from_response_iterator
2020-07-13T03:23:08.7768786Z     return await response_iterator.__anext__(), True
2020-07-13T03:23:08.7769034Z   File "/home/runner/work/jina/jina/jina/peapods/gateway.py", line 149, in Call
2020-07-13T03:23:08.7769218Z     with AsyncZmqlet(self.args, logger=self.logger) as zmqlet:
2020-07-13T03:23:08.7769420Z   File "/home/runner/work/jina/jina/jina/peapods/zmq.py", line 66, in __init__
2020-07-13T03:23:08.7769599Z     self.ctx, self.in_sock, self.out_sock, self.ctrl_sock = self.init_sockets()
2020-07-13T03:23:08.7769809Z   File "/home/runner/work/jina/jina/jina/peapods/zmq.py", line 163, in init_sockets
2020-07-13T03:23:08.7769975Z     raise ex
2020-07-13T03:23:08.7770167Z   File "/home/runner/work/jina/jina/jina/peapods/zmq.py", line 147, in init_sockets
2020-07-13T03:23:08.7770331Z     self.args.identity)
2020-07-13T03:23:08.7770528Z   File "/home/runner/work/jina/jina/jina/peapods/zmq.py", line 658, in _init_socket
2020-07-13T03:23:08.7770692Z     raise ex
2020-07-13T03:23:08.7770884Z   File "/home/runner/work/jina/jina/jina/peapods/zmq.py", line 655, in _init_socket
2020-07-13T03:23:08.7771376Z     sock.bind('tcp://%s:%d' % (host, port))
2020-07-13T03:23:08.7771609Z   File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
2020-07-13T03:23:08.7771979Z   File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
2020-07-13T03:23:08.7772131Z zmq.error.ZMQError: Address already in use
```

**Closed** 2020-07-13 10:28 UTC
Labels: kind/problem, priority/P0
