### ISSUE TITLE
The doc's embedding is always "None", even after docs flowing through the Encoder Executor.

### ISSUE THREAD

**Issue by iamoscar1** [jina-ai/jina#3972] opened 2021-11-22 10:36 UTC
Hi everyone, I am just a beginner of using Jina. Today, I was trying to use the TransformerTorchEncoder from JinaHub and running its example.  The code is attached below:
![截屏2021-11-22 下午6 28 22](https://user-images.githubusercontent.com/19730689/142845396-2da43e32-04b3-4f2a-99fb-234eeb49b79f.png)

According to the description, after running those codes, there should be some values saved in doc.embedding. However, when I checked it,  the embedding attribute is None. Did I miss some important process?

**Environment**
- jina 2.4.7
- jina-proto 0.0.86
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.21.2
- protobuf 3.18.1
- proto-backend cpp
- grpcio 1.41.0
- pyyaml 6.0
- python 3.8.12
- platform Linux
- platform-release 4.20.0-042000-lowlatency
- platform-version #201812232030 SMP PREEMPT Mon Dec 24 01:42:05 UTC 2018
- architecture x86_64
- processor x86_64
- uid 119377531596300
- session-id 76df6b99-4b7f-11ec-8f6d-6c92bf5d6e0c
- uptime 2021-11-22T18:32:16.313072
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_K8S_USE_TEST_PIP (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)

**Screenshots**

![截屏2021-11-22 下午6 34 25](https://user-images.githubusercontent.com/19730689/142846363-ead15506-d767-4994-8902-09830064461c.png)

**Comment by JoanFM** [comment] 2021-11-22 10:41
can u share the logs shown?

It would be great if you can also set `JINA_LOG_LEVEL` environment variable to `DEBUG`

**Comment by iamoscar1** [comment] 2021-11-22 11:09
> can u share the logs shown?
> 
> It would be great if you can also set `JINA_LOG_LEVEL` environment variable to `DEBUG`
Thank you so much for your quick response!
Sure, I will past all the logging content through screen shots.
### 
![截屏2021-11-22 下午7 05 06](https://user-images.githubusercontent.com/19730689/142851089-0228673a-54e8-46c6-87a3-da1f89e8f71d.png)
![截屏2021-11-22 下午7 05 18](https://user-images.githubusercontent.com/19730689/142851106-568e7da5-0f3f-4933-a624-93a744c68653.png)

![截屏2021-11-22 下午7 05 29](https://user-images.githubusercontent.com/19730689/142851120-d0befab8-dd41-4f91-a304-fd28f271ab9e.png)
![截屏2021-11-22 下午7 05 40](https://user-images.githubusercontent.com/19730689/142851146-b692c76d-3bdd-4b99-a55f-8ba6be377ae2.png)

**Comment by JoanFM** [comment] 2021-11-22 11:43
Hey @iamoscar1 ,

I am not being able to reproduce with the model that you show. The error given is this one:

```
- 'FinBERT_L-12_H-768_A-12_pytorch' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'FinBERT_L-12_H-768_A-12_pytorch' is the correct path to a directory containing a config.json file
```

I have tried without this model and the embedding seems to be there.

How can I get this model to try and investigate further?

**Comment by iamoscar1** [comment] 2021-11-22 13:16
> Hey @iamoscar1 ,
> 
> I am not being able to reproduce with the model that you show. The error given is this one:
> 
> ```
> OSError: Can't load config for 'FinBERT_L-12_H-768_A-12_pytorch'. Make sure that:
> 
> - 'FinBERT_L-12_H-768_A-12_pytorch' is a correct model identifier listed on 'https://huggingface.co/models'
> 
> - or 'FinBERT_L-12_H-768_A-12_pytorch' is the correct path to a directory containing a config.json file
> ```
> 
> I have tried without this model and the embedding seems to be there.
> 
> How can I get this model to try and investigate further?

Oh, sorry, my bad. I forget to mention  this model is a local-saved model. Never mind, I have tried again to use the suggested model as listed in TransformerTorchEncoder 's Usage. The result remains the same, None.
Details are showed in the form of screenshots listed below:
<img width="953" alt="截屏2021-11-22 下午9 13 19" src="https://user-images.githubusercontent.com/19730689/142868137-e2ffe977-2f9b-4863-adbc-79ae9abaf2a9.png">
<img width="955" alt="截屏2021-11-22 下午9 14 00" src="https://user-images.githubusercontent.com/19730689/142868151-9be70577-14dc-4187-9b3e-0715e0348850.png">
<img width="926" alt="截屏2021-11-22 下午9 14 24" src="https://user-images.githubusercontent.com/19730689/142868171-cd464c76-a103-4e47-8a9d-8c64e9f9fab8.png">
<img width="982" alt="截屏2021-11-22 下午9 14 37" src="https://user-images.githubusercontent.com/19730689/142868182-687e6a68-a7b6-44d6-bdb4-0459c5bfc8ae.png">
<img width="989" alt="截屏2021-11-22 下午9 14 47" src="https://user-images.githubusercontent.com/19730689/142868193-33933482-3bc0-4925-9292-2a3f36ec92b8.png">

<img width="870" alt="截屏2021-11-22 下午9 14 59" src="https://user-images.githubusercontent.com/19730689/142868202-8f0c27c2-c969-451e-afaa-7f144a4ba8ff.png">

Once again, thank you for ur help!

**Comment by JoanFM** [comment] 2021-11-22 13:27
Okey, my bad.

What you are expecting is not true.

So what you are trying to do is this:

```python
from jina import Flow, Document

 f = Flow().add(uses='jinahub://TransformerTorchEncoder')
doc = Document(content='this is a sentence to be encoded')
with f:
    results = f.post(on='/foo', inputs=doc, return_results=True)

print(results[0].docs[0].embedding) # this will be filled
print(doc.embedding) # this will be None
```

The `doc` in the request is not changed, a new `Document` is returned with the `embedding` filled. I guess there is a missunderstanding of the usage. What the `Flow` is doing is calling a client to send the `Document` through the network, therefore the `Executor` does not operate directly in the same `object` as the `client` has access to, but to the one sent to the `Executor`.

I hope this clarifies, and you can validate the behavior observed

**Comment by iamoscar1** [comment] 2021-11-22 13:40
> Okey, my bad.
> 
> What you are expecting is not true.
> 
> So what you are trying to do is this:
> 
> ```python
> from jina import Flow, Document
> 
>  f = Flow().add(uses='jinahub://TransformerTorchEncoder')
> doc = Document(content='this is a sentence to be encoded')
> with f:
>     results = f.post(on='/foo', inputs=doc, return_results=True)
> 
> print(results[0].docs[0].embedding) # this will be filled
> print(doc.embedding) # this will be None
> ```
> 
> The `doc` in the request is not changed, a new `Document` is returned with the `embedding` filled. I guess there is a missunderstanding of the usage. What the `Flow` is doing is calling a client to send the `Document` through the network, therefore the `Executor` does not operate directly in the same `object` as the `client` has access to, but to the one sent to the `Executor`.
> 
> I hope this clarifies, and you can validate the behavior observed
😭😭😭，thank you so much for your explanation! You've just saved me from a horrible day.

**Comment by JoanFM** [comment] 2021-11-22 13:44
Happy to hear @iamoscar1 ! I assume then that your problem is solved. I will close this issue for now. Do not hesitate to open it back or to add any other issue if you have any other problem or doubt.

**Closed by JoanFM** 2021-11-22 13:44 UTC
