### ISSUE TITLE
kubernetes deployment: can not load the executor from config.yml 

### ISSUE THREAD

**Issue by hsalehgh** [jina-ai/jina#4987] opened 2022-06-30 16:20 UTC
First Thank you so much for your great platform and on time responses. I am trying to deploy a simple flow in kubernetes. I have dockerzied my exceutor and indexer based on jina document and run dockers and both where working fine. Here is my docker file for indexer:
**config.yaml:**
```yaml
jtype: SimpleIndexer
uses_with:
  match_args: {}
uses_metas:
  name: SimpleIndexer
  description: "SimpleIndexer does indexing and searching"
  py_modules:
    - simple_indexer.py
  workspace: './workspace'
uses_request:
  /index: index
  /search: search
```
**simple_indexer.py**

```python
import inspect
import os
from typing import Dict, Optional

from jina import DocumentArray, Executor, requests
from jina.logging.logger import JinaLogger


class SimpleIndexer(Executor):


    FILE_NAME = 'index.db'

    def __init__(
        self,
        match_args: Optional[Dict] = None,
        table_name: str = 'simple_indexer_table',
        traversal_right: str = '@r',
        traversal_left: str = '@r',
        **kwargs,
    ):
  
        super().__init__(**kwargs)

        self._match_args = match_args or {}
        self._index = DocumentArray(
            storage='sqlite',
            config={
                'connection': SimpleIndexer.FILE_NAME,
                'table_name': table_name,
            },
        )  # with customize config
        self.logger = JinaLogger(self.metas.name)
        self.default_traversal_right = traversal_right
        self.default_traversal_left = traversal_left

    @property
    def table_name(self) -> str:
        return self._index._table_name

    @requests(on='/index')
    def index(
        self,
        docs: 'DocumentArray',
        **kwargs,
    ):
        """All Documents to the DocumentArray
        :param docs: the docs to add
        """
        if docs:
            self._index.extend(docs)

    @requests(on='/search')
    def search(
        self,
        docs: 'DocumentArray',
        parameters: Optional[Dict] = None,
        **kwargs,
    ):
        """Perform a vector similarity search and retrieve the full Document match

        :param docs: the Documents to search with
        :param parameters: the runtime arguments to `DocumentArray`'s match
        function. They overwrite the original match_args arguments.
        """
        match_args = (
            {**self._match_args, **parameters}
            if parameters is not None
            else self._match_args
        )

        traversal_right = parameters.get(
            'traversal_right', self.default_traversal_right
        )
        traversal_left = parameters.get('traversal_left', self.default_traversal_left)
        match_args = SimpleIndexer._filter_match_params(docs, match_args)
        docs[traversal_left].match(self._index[traversal_right], **match_args)

    @staticmethod
    def _filter_match_params(docs, match_args):
        # get only those arguments that exist in .match
        args = set(inspect.getfullargspec(docs.match).args)
        args.discard('self')
        match_args = {k: v for k, v in match_args.items() if k in args}
        return match_args

    @requests(on='/delete')
    def delete(self, parameters: Dict, **kwargs):
        """Delete entries from the index by id

        :param parameters: parameters to the request
        """
        deleted_ids = parameters.get('ids', [])
        if len(deleted_ids) == 0:
            return
        del self._index[deleted_ids]

    @requests(on='/update')
    def update(self, docs: DocumentArray, **kwargs):
        """Update doc with the same id, if not present, append into storage

        :param docs: the documents to update
        """

        for doc in docs:
            try:
                self._index[doc.id] = doc
            except IndexError:
                self.logger.warning(
                    f'cannot update doc {doc.id} as it does not exist in storage'
                )

    @requests(on='/fill_embedding')
    def fill_embedding(self, docs: DocumentArray, **kwargs):
        """retrieve embedding of Documents by id

        :param docs: DocumentArray to search with
        """
        for doc in docs:
            doc.embedding = self._index[doc.id].embedding

    @requests(on='/clear')
    def clear(self, **kwargs):
        """clear the database"""
        self._index.clear()
```
And at the end this is my flow:

```python
f = Flow(port=8080).add(name='torch_encoder', uses='docker://ACOUNTNUMBER.dkr.ecr.us-west-2.amazonaws.com/hs-torch-encoder:0.1').add(name='torch_indexer', uses='docker://ACOUNTNUMBER.dkr.ecr.us-west-2.amazonaws.com/hs-torch-indexer:0.1')
f.to_kubernetes_yaml('./k8s_flow', k8s_namespace='test-flow')

```
When I do `kubectl apply -R -f ./k8s_flow`  the status of the indexer pod is **CrashLoopBackOff** and when I look at the logs of the pod I see the following error:
`CRITI… torch_indexer@ 1 can not load the executor from config.yml`

Also when I run flow locally it perfectly works. Any help is really appreciated!

**Comment by JoanFM** [comment] 2022-06-30 16:28
can u share the details on how u have created the 2 docker images so that we can try to reproduce with the most similar setting possible?

**Comment by hsalehgh** [comment] 2022-06-30 16:45
Here is how I created docker file:
```
FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
    git \
    python3.7 \
    python3-pip \
    vim

RUN pip install jina

#Setup Workdir
RUN mkdir /executor_root

COPY . /executor_root/

WORKDIR /executor_root

RUN pip install -r gpu_requirements.txt

ENTRYPOINT ["jina", "executor", "--uses", "config.yml"]
```

**Comment by hsalehgh** [comment] 2022-06-30 17:39
This is also k8s yaml file generated by `f.to_kubernetes_yaml` in case you need
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: torch-indexer
  namespace: test-flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torch-indexer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: torch-indexer
        jina_deployment_name: torch_indexer
        ns: test-flow
        pod_type: WORKER
        shard_id: '0'
    spec:
      containers:
      - args:
        - executor
        - --name
        - torch_indexer
        - --k8s-namespace
        - test-flow
        - --uses
        - config.yml
        - --port
        - '8080'
        - --port-monitoring
        - '9090'
        - --uses-metas
        - '{}'
        - --native
        command:
        - jina
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: JINA_DEPLOYMENT_NAME
          value: torch_indexer
        envFrom:
        - configMapRef:
            name: torch-indexer-configmap
        image: ACCOUNTNUMBER.dkr.ecr.us-west-2.amazonaws.com/hs-torch-indexer:0.1
        imagePullPolicy: IfNotPresent
        name: executor
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 8080
```

**Comment by hsalehgh** [comment] 2022-07-01 10:09
I double checked and I named my config file config.yml for both executors.

**Comment by JoanFM** [comment] 2022-07-01 14:38
can you share the `gpu_requirements.txt`? Also it would be interesting to set `JINA_LOG_LEVEL=DEBUG` inside the Deployments and then share the logs of the failing Pods to see if we can get more information.

 ```yaml
        - name: JINA_DEPLOYMENT_NAME
          value: torch_indexer
        - name: JINA_LOG_LEVEL
          value: DEBUG
```

**Comment by hsalehgh** [comment] 2022-07-01 15:29
> ```yaml
> JINA_LOG_LEVEL
> ```

gpu_requirements.txt:
torch==1.9.0
transformers==4.5.1

Also I did `JINA_LOG_LEVEL=DEBUG` in deployment yml file but it provides same information:
```
CRITI… torch_indexer@ 1 can not load the executor from       [07/01/22 15:28:31]
       config.yml
Traceback (most recent call last):
  File "/usr/local/bin/jina", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/jina_cli/__init__.py", line 143, in main
    getattr(api, args.cli.replace('-', '_'))(args)
  File "/usr/local/lib/python3.8/dist-packages/jina_cli/api.py", line 76, in executor
    return executor_native(args)
  File "/usr/local/lib/python3.8/dist-packages/jina_cli/api.py", line 57, in executor_native
    with runtime_cls(args) as rt:
  File "/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/worker/__init__.py", line 31, in __init__
    super().__init__(args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/asyncio.py", line 66, in __init__
    self._loop.run_until_complete(self.async_setup())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/worker/__init__.py", line 58, in async_setup
    await self._async_setup_grpc_server()
  File "/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/worker/__init__.py", line 68, in _async_setup_grpc_server
    self._data_request_handler = DataRequestHandler(
  File "/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/request_handlers/data_request_handler.py", line 41, in __init__
    self._load_executor(metrics_registry)
  File "/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/request_handlers/data_request_handler.py", line 79, in _load_executor
    self._executor: BaseExecutor = BaseExecutor.load_config(
  File "/usr/local/lib/python3.8/dist-packages/jina/jaml/__init__.py", line 760, in load_config
    obj = JAML.load(tag_yml, substitute=False, runtime_args=runtime_args)
  File "/usr/local/lib/python3.8/dist-packages/jina/jaml/__init__.py", line 174, in load
    r = yaml.load(stream, Loader=get_jina_loader_with_runtime(runtime_args))
  File "/usr/local/lib/python3.8/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.8/dist-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.8/dist-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python3.8/dist-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python3.8/dist-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!SimpleIndexer'
  in "<unicode string>", line 1, column 1:
    !SimpleIndexer
```

**Comment by hsalehgh** [comment] 2022-07-01 15:32
> Also,
> 
> Can you try starting locally a bash session inside the SimpleIndexer image and run this command?
> 
> ```shell
> jina executor --name torch_indexer --uses config,yml  --native 
> ```
> 
> and see what does it say?

When I run this command inside the image, this is the error that I get:
```
ERROR  torch_indexer@14 fail to load file dependency                                                                                                                                                                                                                                                                                                     [07/01/22 15:31:26]
Traceback (most recent call last):
  File "/usr/local/bin/jina", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/jina_cli/__init__.py", line 143, in main
    getattr(api, args.cli.replace('-', '_'))(args)
  File "/usr/local/lib/python3.8/dist-packages/jina_cli/api.py", line 76, in executor
    return executor_native(args)
  File "/usr/local/lib/python3.8/dist-packages/jina_cli/api.py", line 57, in executor_native
    with runtime_cls(args) as rt:
  File "/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/worker/__init__.py", line 31, in __init__
    super().__init__(args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/asyncio.py", line 66, in __init__
    self._loop.run_until_complete(self.async_setup())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/worker/__init__.py", line 58, in async_setup
    await self._async_setup_grpc_server()
  File "/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/worker/__init__.py", line 68, in _async_setup_grpc_server
    self._data_request_handler = DataRequestHandler(
  File "/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/request_handlers/data_request_handler.py", line 41, in __init__
    self._load_executor(metrics_registry)
  File "/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/request_handlers/data_request_handler.py", line 79, in _load_executor
    self._executor: BaseExecutor = BaseExecutor.load_config(
  File "/usr/local/lib/python3.8/dist-packages/jina/jaml/__init__.py", line 688, in load_config
    stream, s_path = parse_config_source(
  File "/usr/local/lib/python3.8/dist-packages/jina/jaml/helper.py", line 169, in parse_config_source
    comp_path = complete_path(path, extra_search_paths)
  File "/usr/local/lib/python3.8/dist-packages/jina/jaml/helper.py", line 218, in complete_path
    raise FileNotFoundError(f'can not find {path}')
FileNotFoundError: can not find config,yml
```

**Comment by hsalehgh** [comment] 2022-07-01 15:38
Also `docker run -it ACOUNTNUMBER.dkr.ecr.us-west-2.amazonaws.com/hs-torch-indexer:0.1` works with no error

**Comment by JoanFM** [comment] 2022-07-02 09:35
> > Also,
> > Can you try starting locally a bash session inside the SimpleIndexer image and run this command?
> > ```shell
> > jina executor --name torch_indexer --uses config,yml  --native 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and see what does it say?
> 
> When I run this command inside the image, this is the error that I get:
> 
> ```
> ERROR  torch_indexer@14 fail to load file dependency                                                                                                                                                                                                                                                                                                     [07/01/22 15:31:26]
> Traceback (most recent call last):
>   File "/usr/local/bin/jina", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.8/dist-packages/jina_cli/__init__.py", line 143, in main
>     getattr(api, args.cli.replace('-', '_'))(args)
>   File "/usr/local/lib/python3.8/dist-packages/jina_cli/api.py", line 76, in executor
>     return executor_native(args)
>   File "/usr/local/lib/python3.8/dist-packages/jina_cli/api.py", line 57, in executor_native
>     with runtime_cls(args) as rt:
>   File "/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/worker/__init__.py", line 31, in __init__
>     super().__init__(args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/asyncio.py", line 66, in __init__
>     self._loop.run_until_complete(self.async_setup())
>   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
>     return future.result()
>   File "/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/worker/__init__.py", line 58, in async_setup
>     await self._async_setup_grpc_server()
>   File "/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/worker/__init__.py", line 68, in _async_setup_grpc_server
>     self._data_request_handler = DataRequestHandler(
>   File "/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/request_handlers/data_request_handler.py", line 41, in __init__
>     self._load_executor(metrics_registry)
>   File "/usr/local/lib/python3.8/dist-packages/jina/serve/runtimes/request_handlers/data_request_handler.py", line 79, in _load_executor
>     self._executor: BaseExecutor = BaseExecutor.load_config(
>   File "/usr/local/lib/python3.8/dist-packages/jina/jaml/__init__.py", line 688, in load_config
>     stream, s_path = parse_config_source(
>   File "/usr/local/lib/python3.8/dist-packages/jina/jaml/helper.py", line 169, in parse_config_source
>     comp_path = complete_path(path, extra_search_paths)
>   File "/usr/local/lib/python3.8/dist-packages/jina/jaml/helper.py", line 218, in complete_path
>     raise FileNotFoundError(f'can not find {path}')
> FileNotFoundError: can not find config,yml
> ```

And when u do `ls` before running the command? what do u see? and if u run `pwd`

**Comment by JoanFM** [comment] 2022-07-02 16:59
This is quite weird because the local image and the one in Kubernetes are giving different problems.

1. The one in K8s is saying that it cannot load SimpleIndexer because cannot find this class (which makes me think is not finding `simple_indexer` path.
2. The one in local is giving a problem about not finding `config.yml`.

This makes me wonder if you are certain that the image in the registry is the one you have in your local

**Comment by hsalehgh** [comment] 2022-07-04 03:48
Actually the local one works perfectly. The problem was I was copying exactly the command you mentioned and it was **config,yml**  not **config.yml**

**Comment by hsalehgh** [comment] 2022-07-04 03:49
Also, to make sure I am using the same image, I deleted all docker files in my local and only pulled the one used in k8s. but still have problem with k8s

**Comment by samsja** [comment] 2022-07-04 06:45
Hey @hsalehgh 

Where is your k8s cluster hosted, cloud provider (which one?) or on premise?

Could you please try to re push your docker image (the one that work locally) to your docker image repository.

On your kuberernetes files generated by jina could you edit this line 

```yaml
        imagePullPolicy: IfNotPresent
```

and replace it by 

```yaml
        imagePullPolicy: Always
```

I suspect that k8s never download the last image that you pushed because of the tags of your docker image might be similar.

**Comment by hsalehgh** [comment] 2022-07-05 11:51
I am using EKS service of AWS. I also made that modification but still receive the same error. When I do `kubectl describe pod` here is what I get as well. It shows that it pulls the right image but for some reasons it gives **Back-off restarting failed container** message
![Screen Shot 2022-07-05 at 7 46 40 AM](https://user-images.githubusercontent.com/23532128/177320954-d89ab24d-6833-4552-8a73-e2eed91e7de4.png)

**Comment by JoanFM** [comment] 2022-07-05 11:59
And what are the logs from the Pod when `JINA_LOG_LEVEL=DEBUG` is set inside the K8s Pod?

**Comment by hsalehgh** [comment] 2022-07-05 16:13
you can download indexer and encoder from the following link and then use  `docker load < indexer.tar`  and `docker load < encoder.tar` 

https://drive.google.com/file/d/1Tkhfye_3MegrNllxagmoDSnGDR3VDCtE/view?usp=sharing

https://drive.google.com/file/d/15GPQS5qdk_Aw408EIpbdjzflLX-RB52T/view?usp=sharing

**Comment by samsja** [comment] 2022-07-06 09:09
@hsalehgh thanks for your help on providing a minimal reproducible example to debug.

I can reproduce the same issue. We will investigate why it is not working properly with the default configuration I suspect that something is different in your Executor and/or in your docker image and that's why it is failing for you.

In the meantime here is an easy fix, you need to remove the lines 
```
 - --uses-metas
 - '{}'
```
from the `torch-indexer.yml` file in the Deployments. 
With that your Flow will work on k8s

**Comment by JoanFM** [comment] 2022-07-07 06:37
Hey @hsalehgh,

did this work? if so, we will close this ticket and open one more descriptive of the underlying problem

**Closed** 2022-07-07 11:46 UTC
Labels: area/community
