### ISSUE TITLE
BinaryPbIndexer should not increase in size when adding a document with an existing id

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/jina#2369] opened 2021-04-30 08:50 UTC
```python
def test_dbms_keyvalue(tmpdir, test_metas):
    docs = list(get_documents(chunks=False, nr=10, same_content=True))
    ids, vecs, metas = _get_ids_vecs_meta(docs)

    save_path = None
    with KeyValueDBMSIndexer(index_filename='dbms', metas=test_metas) as indexer:
        indexer.add(ids, vecs, metas)
        assert indexer.size == len(docs)
        save_path = indexer.save_abspath
        indexer.dump(os.path.join(tmpdir, 'dump1'), 2)

        # we can index and dump again in the same context
        docs2 = list(
            get_documents(chunks=False, nr=10, same_content=True, index_start=0)
        )
        ids, vecs, metas = _get_ids_vecs_meta(docs2)
        indexer.add(ids, vecs, metas)
        assert indexer.size == 2 * len(docs)   # this is true, but should be False, as the ids are the same
        indexer.dump(os.path.join(tmpdir, 'dump2'), 3)
```

Based on tests.unit.executors.dbms.test_dbms.test_dbms_keyvalue

**Comment by JoanFM** [comment] 2021-04-30 10:39
I think this was discussed maybe? That the responsability should be on the user side? @maximilianwerk do u remember that? The cost of closing and opening the file in every `add` operation may be too much?

**Comment by FionnD** [comment] 2021-04-30 14:52
If this is expected behaviour: It should go into docs. 

If this is not expected behavior. It's a critical bug to be solved. 

Waiting on your reply @maximilianwerk

**Comment by cristianmtr** [comment] 2021-04-30 15:57
the problem is also: the underlying data **does** get written to disk. so the size is technically correct. it's just that we can never access it, because the header is a dictionary (and you only have one key with a specific value in a dictionary). all the other docs getting written are hidden. I think this should not happen

**Comment by FionnD** [comment] 2021-06-03 08:58
Hi @cristianmtr @maximilianwerk 

Just coming back to this issue now since we are cleaning the backlog. We need to make a decision if this is expected behavior as Joan said, or a bug that needs to be fixed. Max what is your view?

**Comment by maximilianwerk** [comment] 2021-06-03 09:31
I think it is expected behavior. Let's close this issue.

**Closed by maximilianwerk** 2021-06-03 09:31 UTC
Labels: area/core, component/executor, epic/CRUD
